language: python
virtualenv: 
  system_site_packages: true
sudo: false
addons:
  apt:
    packages:
    - yum
    - python-rpm
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script: 
  - pep8 --show-source --show-pep8 setup.py planex tests
  - pylint setup.py planex
  - nosetests --verbose
