import os
from planex.util import (bcolours, print_col)

makefile_path = "/usr/share/planex"

def create_makefile():
   name = "Makefile"
   if os.path.exists(name):
       print_col(bcolours.WARNING,"Not overwriting existing Makefile")
       return

   print_col(bcolours.OKGREEN,"Creating Makefile")
   with open(name,'w') as h:
       h.write("# Start generated by planex-init\n")
       h.write("include %s/Makefile.rules\n" % (makefile_path))
       h.write("# End generated by planex-init\n")
   print_col(bcolours.OKGREEN,"Makefile created")

def main():
    create_makefile()
