# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
yum install -y git mercurial python-setuptools rpm-build
rpm -ivh http://mirror.ancl.hawaii.edu/linux/epel/6/i386/epel-release-6-8.noarch.rpm
yum install -y mock
cd /home/vagrant
su vagrant <<EOF
wget --no-check-certificate https://raw.github.com/pypa/pip/master/contrib/get-pip.py
sudo python get-pip.py
sudo pip install virtualenv
virtualenv --system-site-packages env
. env/bin/activate
pip install -r /planex/test-requirements.txt
pip install tox
cp /planex/vagrant/test.sh /home/vagrant
chmod 755 /home/vagrant/test.sh
EOF
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "jonludlam/xs-centos-6.5"
  config.vm.provision "shell", inline: $script

  config.vm.synced_folder "../", "/planex", type: "nfs"

end
