FROM centos:7.2.1511
MAINTAINER Euan Harris <euan.harris@citrix.com>
RUN yum -y install sudo epel-release
RUN yum -y install https://xenserver.github.io/planex-release/unstable/rpm/el/planex-unstable-7-1.noarch.rpm
RUN yum -y install make git  # Planex spec file should list these as requirements
RUN yum -y install planex
RUN useradd build --groups mock,wheel --home-dir /build
COPY entry.sh /entry.sh
ENTRYPOINT ["/entry.sh"]
