FROM centos:7.2.1511
MAINTAINER Euan Harris <euan.harris@citrix.com>
RUN yum -y install \
  epel-release \
  https://xenserver.github.io/planex-release/release/rpm/el/planex-release-7-1.noarch.rpm \
  sudo
RUN yum -y install planex
RUN mkdir /build
COPY entry.sh /entry.sh
ENTRYPOINT ["bash", "/entry.sh"]
